### ISSUE TITLE
Create status handler

### ISSUE THREAD

**Issue by apfong** [UCLA-CS130/Mr.-Robot-et-al.#51]
Should be at the `/status` route.
Should output how many requests have been received, broken down by the url requested and status code.
Should also output what handlers exist and what prefixes are mapped to them.

```
Possible output:

Available handlers:
EchoHandler     <--- /echo
StaticHandler   <--- /static
StatusHandler   <--- /status
NotFoundHandler <--- default

Count | URL Requested | Response Code
-----------------------------------
2     | .../echo      | 400
10    | .../echo      | 200
4     | .../echo      | 404
6     | .../static    | 200
42    | .../status    | 200
```

**Comment by KyCodeHuynh** [comment]
Implementation idea: Observer pattern. We construct an ServerStats object in `LightningServer`, which has methods like `recordRequest()`. That lets us track the number of requests and their types. That same object (or rather, a pointer to it) can be passed to RequestRouter's constructor, so that we have a global that our StatusHandler instance can read when `/status` is visited.

**Comment by KyCodeHuynh** [comment]
Completed by PR #56.
